name: flutter_datetime_webapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  timezone: ^0.9.2
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flex_color_scheme: ^7.3.1
  weather: ^3.1.1
  http: ^1.2.0
  flutter_analog_clock: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
